use_frameworks!

platform :ios, '9.0'

target 'TCBFreshchatBotWidget_Example' do
  pod 'TCBFreshchatBotWidget', :path => '../'

  target 'TCBFreshchatBotWidget_Tests' do
    inherit! :search_paths

    
  end
end
